import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  outputFileTracingRoot: process.cwd(),
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "catalog.wlimg.com" },
      { protocol: "https", hostname: "ttw.wlimg.com" },
      { protocol: "https", hostname: "dynamic.tourtravelworld.com" },
      { protocol: "https", hostname: "static.tourtravelworld.com" },
    ],
  },
  async redirects() {
    return [
      { source: "/about-us.htm", destination: "/about", permanent: true },
      { source: "/tour-packages.htm", destination: "/packages", permanent: true },
      { source: "/tour-operators.htm", destination: "/services/tour-operators", permanent: true },
      { source: "/mice-services.htm", destination: "/services/mice", permanent: true },
      { source: "/filpbook.htm", destination: "/brochure", permanent: true },
      { source: "/contact-us.htm", destination: "/contact", permanent: true },
      { source: "/enquiry-form-10005.htm", destination: "/enquiry", permanent: true },
      { source: "/testimonials.htm", destination: "/testimonials", permanent: true },
      { source: "/career.htm", destination: "/career", permanent: true },
      { source: "/terms-condition.htm", destination: "/terms", permanent: true },
      { source: "/currency-converter.htm", destination: "/currency", permanent: true },
      { source: "/sitemap.htm", destination: "/sitemap", permanent: true },
      { source: "/culture-heritage-theme.htm", destination: "/themes/culture-heritage", permanent: true },
      { source: "/family-group-tours-theme.htm", destination: "/themes/family-group", permanent: true },
      { source: "/religious-pilgrimage-theme.htm", destination: "/themes/religious-pilgrimage", permanent: true },
      { source: "/Monuments-Historical-places-theme.htm", destination: "/themes/monuments", permanent: true },
      { source: "/honeymoon-romantic-tours-theme.htm", destination: "/themes/honeymoon", permanent: true },
      { source: "/women-friendly-tours-theme.htm", destination: "/themes/women-friendly", permanent: true },
      { source: "/luxury-tours-theme.htm", destination: "/themes/luxury", permanent: true },
      { source: "/winter-tours-theme.htm", destination: "/themes/winter", permanent: true },
      { source: "/heritage-holidays-catid.htm", destination: "/activities/heritage", permanent: true },
      { source: "/forts-palaces-holidays-catid.htm", destination: "/activities/forts-palaces", permanent: true },
      { source: "/lakes-rivers-holidays-catid.htm", destination: "/activities/lakes-rivers", permanent: true },
      { source: "/family-holidays-catid.htm", destination: "/activities/family", permanent: true },
      { source: "/jungle-safari-holidays-catid.htm", destination: "/activities/jungle-safari", permanent: true },
      { source: "/group-holidays-catid.htm", destination: "/activities/group", permanent: true },
      { source: "/hill-station-holidays-catid.htm", destination: "/activities/hill-stations", permanent: true },
      { source: "/honeymoon-holidays-catid.htm", destination: "/activities/honeymoon", permanent: true },
      { source: "/packages-in-new-delhi.htm", destination: "/destinations/new-delhi", permanent: true },
      { source: "/packages-in-jaipur.htm", destination: "/destinations/jaipur", permanent: true },
      { source: "/packages-in-agra.htm", destination: "/destinations/agra", permanent: true },
      { source: "/packages-in-jodhpur.htm", destination: "/destinations/jodhpur", permanent: true },
      { source: "/packages-in-jaisalmer.htm", destination: "/destinations/jaisalmer", permanent: true },
      { source: "/packages-in-ranakpur.htm", destination: "/destinations/ranakpur", permanent: true },
      { source: "/packages-in-ranthambore.htm", destination: "/destinations/ranthambore", permanent: true },
      { source: "/packages-in-udaipur.htm", destination: "/destinations/udaipur", permanent: true },
      { source: "/tour-packages/the-golden-triangle-north-india.htm", destination: "/packages/golden-triangle", permanent: true },
      { source: "/tour-packages/pushkar-fair-tour.htm", destination: "/packages/pushkar-fair", permanent: true },
      { source: "/tour-packages/splendorsof-rajasthan-tour.htm", destination: "/packages/splendors-of-rajasthan", permanent: true },
      { source: "/tour-packages/kerala-coconut-holidays-tour.htm", destination: "/packages/kerala-coconut", permanent: true },
      { source: "/tour-packages/footstepsof-buddha-tour.htm", destination: "/packages/footsteps-of-buddha", permanent: true },
      { source: "/tour-packages/taj-temple-ganges-tour.htm", destination: "/packages/taj-temple-ganges", permanent: true },
      { source: "/tour-packages/ladakh-hemis-festival.htm", destination: "/packages/ladakh-hemis", permanent: true },
      { source: "/tour-packages/camel-safariin-rajasthan-tour.htm", destination: "/packages/camel-safari", permanent: true },
      { source: "/tour-packages/luxury-breaks-ranthambor.htm", destination: "/packages/ranthambore-luxury-break", permanent: true },
      { source: "/tour-packages/long-weekend-breaks-the-golden-triangle-tour.htm", destination: "/packages/golden-triangle-long-weekend", permanent: true },
      { source: "/tour-packages/weekend-breaks-agra-sikri-tour.htm", destination: "/packages/agra-fatehpur-weekend", permanent: true },
      { source: "/tour-packages/ayurveda-holidays-tour1.htm", destination: "/packages/ayurveda-holidays", permanent: true },
      { source: "/tour-packages/bestof-north-west-india-with-nepal-tour.htm", destination: "/packages/north-west-india-nepal", permanent: true },
      { source: "/tour-packages/himalayan-trails-valleyof-flowers-trek-tour.htm", destination: "/packages/valley-of-flowers", permanent: true },
      { source: "/tour-packages/golden-triangle-east-india-tour.htm", destination: "/packages/golden-triangle-east", permanent: true },
      { source: "/tour-packages/kashmir-switzerlandof-the-east-tour.htm", destination: "/packages/kashmir-switzerland", permanent: true },
      { source: "/tour-packages/rajasthan-landof-kings-queens-tour.htm", destination: "/packages/rajasthan-kings-queens", permanent: true },
      { source: "/tour-packages/adventure-india-wildlife-escapades.htm", destination: "/packages/adventure-wildlife", permanent: true },
      { source: "/tour-packages/sun-sand-cave-temples.htm", destination: "/packages/sun-sand-caves", permanent: true },
      { source: "/tour-packages/rajasthan-shekhawati-region-tour.htm", destination: "/packages/rajasthan-shekhawati", permanent: true },
      { source: "/tour-packages/luxury-cruisein-kerala-gods-own-country-tour1.htm", destination: "/packages/kerala-luxury-cruise", permanent: true },
      { source: "/tour-packages/the-mysterious-islandsof-andaman-and-nicobar-tour.htm", destination: "/packages/andaman-nicobar", permanent: true },
      { source: "/inbound-tours.htm", destination: "/services/inbound", permanent: true },
      { source: "/outbound-tours.htm", destination: "/services/outbound", permanent: true },
      { source: "/heritage-cultural-tours.htm", destination: "/services/heritage-cultural", permanent: true },
      { source: "/beach-island-tours.htm", destination: "/services/beach-island", permanent: true },
      { source: "/pilgrimage-tours.htm", destination: "/services/pilgrimage", permanent: true },
      { source: "/ayurveda-wellness-tours.htm", destination: "/services/ayurveda-wellness", permanent: true },
      { source: "/blog/", destination: "/blog", permanent: true },
    ];
  },
  async rewrites() {
    return [{ source: "/tour-packages.rss", destination: "/rss" }];
  },
};

export default nextConfig;
